# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

linter:
  rules:
    lines_longer_than_80_chars: false
    omit_local_variable_types: false
    flutter_style_todos: false
    one_member_abstracts: false
    avoid_function_literals_in_foreach_calls: false
