name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.17.0'
        channel: 'stable'
    - name: Flutter analyze
      run: flutter analyze
  build-android:
    runs-on: ubuntu-latest
    needs: [analyze]
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.17.0'
        channel: 'stable'
    - name: Pub get
      run: flutter pub get
    - name: Android build
      run: flutter build apk
  build-ios:
    runs-on: macos-latest
    needs: [analyze]
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.17.0'
        channel: 'stable'
    - name: Pub get
      run: flutter pub get
    - name: iOS build
      run: flutter build ios
