name: Firestore Security rules

on:
  push:
    branches: [ master ]
    paths:
      - firebase/**
  pull_request:
    branches: [ master ]
    paths:
      - firebase/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./firebase
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-
    - name: npm ci
      run: npm ci
    - name: emulator setup
      run: npx firebase setup:emulators:firestore
    - name: emulator start
      run: npx firebase emulators:start --only firestore &
    - name: Sleep for 10 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '10s'
    - name: npm test
      run: npm test
    - name: deploy rule
      run: npx firebase deploy --only firestore:rules --token ${{ secret.FIREBASE_CLI_TOKEN }} 
